uint8 CREATE_DEPTH_MASK = 1
uint8 UPDATE_MARK_MASK = 2
uint8 START_UPDATE_TIMER = 4
uint8 STOP_UPDATE_TIMER = 8
uint8 MARK_RELEASE = 16
uint8 GET_MASKED_IMG = 32

uint8 mode
uint8 mask_id
int16[2] resolution

---

sensor_msgs/Image rgb_img
sensor_msgs/Image depth_img
sensor_msgs/Image segmask
sensor_msgs/CameraInfo rgb_camera_info
sensor_msgs/CameraInfo depth_camera_info
geometry_msgs/Pose[] marker_poses
float32[] corners_depth
bool success